apiVersion: v1
kind: ConfigMap
metadata:
  name: djangoapp-config
  namespace: edu-reverent-mestorf
data:
  SECRET_KEY: 'SECRET_KEY'
  DATABASE_URL: 'DATABASE_UR'
  DEBUG: 'False'
  ALLOWED_HOSTS: 'ALLOWED_HOSTS'
