apiVersion: batch/v1
kind: Job
metadata:
  name: djangoapp-migrate
  namespace: edu-reverent-mestorf
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: djangoapp-migrate
          image: amartyanov1974/test-django:v.1.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: djangoapp-config
          command: ["python", "manage.py", "migrate", "--noinput"]
      restartPolicy: Never
